alter session set "_ORACLE_SCRIPT"=TRUE;

drop user FIDE_PROYECTOG7_USR;
CREATE TABLESPACE FIDE_PROYECTOG7_TBS
DATAFILE 'C:\app\*NombreUsuario*\product\21c\oradata\XE\FIDE_PROYECTOG7_TBS.dbf' 
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;
CREATE USER FIDE_PROYECTOG7_USR IDENTIFIED BY "1234"
DEFAULT TABLESPACE FIDE_PROYECTOG7_TBS
QUOTA UNLIMITED ON FIDE_PROYECTOG7_TBS;
-- Privilegios b�sicos
GRANT CREATE SESSION TO FIDE_PROYECTOG7_TBS;
GRANT RESOURCE TO FIDE_PROYECTOG7_TBS;

GRANT DBA TO FIDE_PROYECTOG7_USR;
GRANT CREATE SESSION TO FIDE_PROYECTOG7_USR;
GRANT RESOURCE TO FIDE_PROYECTOG7_USR;
GRANT CREATE CLUSTER TO FIDE_PROYECTOG7_USR;
GRANT CREATE DIMENSION TO FIDE_PROYECTOG7_USR;
GRANT CREATE INDEXTYPE TO FIDE_PROYECTOG7_USR;
GRANT CREATE JOB TO FIDE_PROYECTOG7_USR;
GRANT CREATE MATERIALIZED VIEW TO FIDE_PROYECTOG7_USR;
GRANT CREATE OPERATOR TO FIDE_PROYECTOG7_USR;
GRANT CREATE PROCEDURE TO FIDE_PROYECTOG7_USR;
GRANT CREATE SEQUENCE TO FIDE_PROYECTOG7_USR;
GRANT CREATE SYNONYM TO FIDE_PROYECTOG7_USR;
GRANT CREATE TABLE TO FIDE_PROYECTOG7_USR;
GRANT CREATE TRIGGER TO FIDE_PROYECTOG7_USR;
GRANT CREATE TYPE TO FIDE_PROYECTOG7_USR;
GRANT CREATE VIEW TO FIDE_PROYECTOG7_USR;

COMMIT;